# Generated by Django 4.2.16 on 2026-01-08 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0006_alter_historicalcontract_table_and_more'),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The person assigned to this task.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people_management.person'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The person who created this task.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people_management.person'),
        ),
    ]
