# Generated by Django 4.2.16 on 2025-12-25 18:32

from django.db import migrations, models
import people_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0006_alter_historicalcontract_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='resume',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[people_management.models.validate_resume]),
        ),
        migrations.AddField(
            model_name='person',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=people_management.models.rename_file, validators=[people_management.models.validate_resume]),
        ),
    ]
