# Generated by Django 4.2.16 on 2026-01-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0006_alter_historicalcontract_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalperson',
            table=None,
        ),
    ]
