# Generated by Django 6.0.1 on 2026-01-16 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0007_alter_historicalperson_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contracted_hours',
            field=models.FloatField(default=40, help_text='Number of contracted hours per week.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='hourly_rate',
            field=models.FloatField(default=12.45, help_text='Hourly pay rate for this contract.', validators=[django.core.validators.MinValueValidator(12.45)]),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contracted_hours',
            field=models.FloatField(default=40, help_text='Number of contracted hours per week.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='hourly_rate',
            field=models.FloatField(default=12.45, help_text='Hourly pay rate for this contract.', validators=[django.core.validators.MinValueValidator(12.45)]),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR Admin', 'HR Admin'), ('System Admin', 'System Admin')], default='Employee', help_text='The role of the person in the company.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR Admin', 'HR Admin'), ('System Admin', 'System Admin')], default='Employee', help_text='The role of the person in the company.', max_length=20),
        ),
    ]
