# Generated by Django 6.0.1 on 2026-01-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_management', '0008_alter_contract_contracted_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR Admin', 'HR Admin'), ('System Admin', 'System Admin')], default='employee', help_text='The role of the person in the company.', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('HR Admin', 'HR Admin'), ('System Admin', 'System Admin')], default='employee', help_text='The role of the person in the company.', max_length=20),
        ),
    ]
