# Generated by Django 4.2.16 on 2026-01-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_securitylog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('LOCKOUT', 'Account Lockout'), ('PERMISSION_DENIED', 'Permission Denied'), ('SUSPICIOUS', 'Suspicious Activity'), ('ADMIN_CREATE_USER', 'Admin Create User'), ('ADMIN_UPDATE_USER', 'Admin Update User'), ('ADMIN_DELETE_USER', 'Admin Delete User'), ('ADMIN_CREATE_GROUP', 'Admin Create Group'), ('ADMIN_UPDATE_GROUP', 'Admin Update Group'), ('ADMIN_DELETE_GROUP', 'Admin Delete Group')], max_length=64),
        ),
    ]
